# Generated by Django 5.2.8 on 2025-11-20 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('type_commande', models.CharField(choices=[('livraison', 'Livraison'), ('sur place', 'Sur place')], max_length=20)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En préparation', 'En préparation'), ('Prête', 'Prête'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
