# Generated by Django 5.2.8 on 2025-12-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandesApp', '0002_commande_qr_code_alter_commande_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='items',
        ),
        migrations.AddField(
            model_name='commande',
            name='items',
            field=models.ManyToManyField(related_name='commandes', to='CommandesApp.menu'),
        ),
    ]
