# Generated by Django 5.2.8 on 2025-12-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandesApp', '0004_plate_remove_commande_items_remove_menu_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plates/'),
        ),
    ]
