# Generated by Django 5.2.8 on 2025-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandesApp', '0005_plate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
