# Generated by Django 5.2.8 on 2025-12-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandesApp', '0006_commande_adresse_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En préparation', 'En préparation'), ('Prête', 'Prête'), ('En cours de livraison', 'En cours de livraison'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=30),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('livraison', 'Livraison'), ('sur place', 'Sur place')], max_length=30),
        ),
    ]
