# Generated by Django 5.2.8 on 2025-11-19 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('prete', 'Prête'), ('en_attente', 'En attente'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('id_livreur', models.IntegerField(blank=True, null=True)),
                ('id_commande', models.IntegerField(blank=True, null=True)),
                ('id_client', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('adresse_complete', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
