# Generated by Django 5.2.8 on 2025-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('prete', 'Prête'), ('en_attente', 'En attente'), ('livree', 'Livrée'), ('retour', 'Retour'), ('annulee', 'Annulée')], default='en_cours', max_length=20),
        ),
    ]
