# Generated by Django 5.2.8 on 2025-12-17 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandesApp', '0005_plate_image'),
        ('LivraisonApp', '0002_alter_livraison_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='Commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='CommandesApp.commande'),
        ),
    ]
