# Generated by Django 5.2.8 on 2025-12-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0003_livraison_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='Commande',
            new_name='commande',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='id_commande',
        ),
    ]
