# Generated by Django 5.2.8 on 2025-12-17 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0004_rename_commande_livraison_commande_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='id_client',
        ),
        migrations.AddField(
            model_name='livraison',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
