# Generated by Django 5.2.8 on 2025-12-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0005_remove_livraison_id_client_livraison_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='adresse_complete',
            new_name='adresse_livraison',
        ),
    ]
