# Generated by Django 5.2.8 on 2025-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0006_rename_adresse_complete_livraison_adresse_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='adresse_livraison',
            field=models.CharField(max_length=255),
        ),
    ]
