# Generated by Django 5.2.8 on 2025-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0007_alter_livraison_adresse_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
