# Generated by Django 5.2.8 on 2025-12-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0008_alter_livraison_adresse_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='longitude',
        ),
    ]
