# Generated by Django 5.2.8 on 2025-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0009_remove_livraison_latitude_remove_livraison_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En préparation', 'En préparation'), ('Prête', 'Prête'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='en_cours', max_length=20),
        ),
    ]
