# Generated by Django 5.2.8 on 2025-12-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivraisonApp', '0010_alter_livraison_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En préparation', 'En préparation'), ('Prête', 'Prête'), ('En cours de livraison', 'En cours de livraison'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='en_cours', max_length=30),
        ),
    ]
