# Generated by Django 5.2.8 on 2025-12-05 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=90, help_text='Durée anticipée en minutes'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='release_task_id',
            field=models.CharField(blank=True, help_text='Celery task id for scheduled release', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reminder_datetime',
            field=models.DateTimeField(blank=True, help_text='Moment où le rappel client doit être envoyé', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Réservé'), ('cancelled', 'Annulé'), ('finished', 'Terminé')], default='reserved', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
