# Generated by Django 5.2.8 on 2025-11-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
