# Generated by Django 5.2.8 on 2025-11-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='zone',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('Standard', 'Standard'), ('Terrasse', 'Terrasse')], max_length=50, null=True),
        ),
    ]
