# Generated by Django 5.2.8 on 2025-12-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_table_number_alter_table_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='ambiance',
            field=models.CharField(blank=True, help_text='Vue / ambiance', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='category',
            field=models.CharField(blank=True, help_text='Catégorie: Standard, VIP, Famille...', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='highchair',
            field=models.BooleanField(default=False, help_text='Chaise haute disponible'),
        ),
        migrations.AddField(
            model_name='table',
            name='location',
            field=models.CharField(blank=True, help_text='Emplacement: intérieur, terrasse...', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='pmr',
            field=models.BooleanField(default=False, help_text='Accessible aux personnes à mobilité réduite'),
        ),
        migrations.AddField(
            model_name='table',
            name='power',
            field=models.BooleanField(default=False, help_text='Prise électrique disponible'),
        ),
        migrations.AddField(
            model_name='table',
            name='special_status',
            field=models.CharField(blank=True, help_text='Statut spécial (ex: événement, VIP)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='wifi',
            field=models.BooleanField(default=False, help_text='Accès Wifi à proximité'),
        ),
    ]
