# Generated by Django 5.2.8 on 2025-11-20 16:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\s-]+$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\s-]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('gerant', 'Gérant'), ('client', 'Client'), ('livreur', 'Livreur')], default='client', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('restaurant_name', models.CharField(blank=True, max_length=255)),
                ('restaurant_address', models.CharField(blank=True, max_length=255)),
                ('restaurant_phone', models.CharField(blank=True, max_length=20)),
                ('siret', models.CharField(blank=True, max_length=50, verbose_name='SIRET')),
                ('business_license', models.CharField(blank=True, max_length=100)),
                ('living_location', models.CharField(blank=True, max_length=255)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=50)),
                ('vehicle_registration', models.CharField(blank=True, max_length=100)),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gerant',
            fields=[
            ],
            options={
                'verbose_name': 'Gérant',
                'verbose_name_plural': 'Gérants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('UserApp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('UserApp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('UserApp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
