# Generated by Django 5.2.8 on 2025-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='preference',
            field=models.CharField(choices=[('chef_special', "Chef's Special"), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('spicy', 'Spicy Lovers'), ('kids', "Kids' Favorite"), ('gluten_free', 'Gluten-Free'), ('seafood', 'Seafood Delights'), ('dessert', 'Dessert'), ('beverage', 'Beverages & Drinks'), ('low_carb', 'Low-Carb')], default='chef_special', max_length=20),
        ),
    ]
