# Generated by Django 5.2.8 on 2025-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='preference',
            field=models.CharField(choices=[('chef_special', "Chef's Special"), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('spicy', 'Spicy Lovers'), ('kids', "Kids' Favorite"), ('dessert', 'Dessert'), ('beverage', 'Beverage')], default='chef_special', max_length=20),
        ),
    ]
