# Generated by Django 5.2.8 on 2025-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dish_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='preferred_sauce',
            field=models.CharField(default='House Signature', help_text='Sauce pairing or garnish that best matches the dish.', max_length=80),
        ),
    ]
