# Generated by Django 5.2.8 on 2025-12-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_dish_preferred_sauce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('appetizers', 'Appetizers'), ('mains', 'Mains'), ('desserts', 'Desserts'), ('beverages', 'Beverages')], max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='🍽️', help_text='Emoji icon for the category', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten-free'), ('dairy_free', 'Dairy-free'), ('keto', 'Keto')], max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='✓', help_text='Emoji icon for the tag', max_length=50)),
                ('color', models.CharField(default='#28a745', help_text='Hex color for badge', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='prep_time',
            field=models.IntegerField(default=15, help_text='Preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='dish',
            name='times_ordered',
            field=models.IntegerField(default=0, help_text='Number of times this dish has been ordered'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='menu.category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='menu.dietarytag'),
        ),
    ]
