# Generated by Django 5.2.8 on 2025-12-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_dietarytag_dish_prep_time_dish_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nuts', 'Nuts'), ('dairy', 'Dairy'), ('eggs', 'Eggs'), ('shellfish', 'Shellfish'), ('soy', 'Soy'), ('wheat', 'Wheat/Gluten')], max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('italian', 'Italian'), ('mexican', 'Mexican'), ('asian', 'Asian'), ('mediterranean', 'Mediterranean'), ('american', 'American'), ('fusion', 'Fusion')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Comma-separated list of ingredients'),
        ),
        migrations.AddField(
            model_name='dish',
            name='spice_level',
            field=models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('extra_hot', 'Extra Hot')], default='mild', max_length=20),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='menu.allergen'),
        ),
    ]
